development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: instagram_automation_development
  username: mahadev-bhat

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: instagram_automation_test
  username: mahadev-bhat

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: instagram_automation_production
  username: instagram_automation
  password: <%= ENV["INSTAGRAM_AUTOMATION_DATABASE_PASSWORD"] %>