default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: dpg-d5cakafgi27c739a1620-a.oregon-postgres.render.com
  port: 5432
  database: linkedin_app_f84j
  username: linkedin_app_f84j_user
  password: gxm6Xa381o7sebY917sxLXVdYC4LhQ4y

test:
  <<: *default
  database: jobextension_test
  host: localhost
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  <<: *default
  host: dpg-d5cakafgi27c739a1620-a
  port: 5432
  database: linkedin_app_f84j
  username: linkedin_app_f84j_user
  password: gxm6Xa381o7sebY917sxLXVdYC4LhQ4y