default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: instagram_automation_development
  username: <%= ENV['USER'] %>
  password:
  host: localhost

test:
  <<: *default
  database: instagram_automation_test
  username: <%= ENV['USER'] %>
  password:
  host: localhost

production:
  <<: *default
  database: instagram_automation_production
  username: instagram_automation
  password: <%= ENV["INSTAGRAM_AUTOMATION_DATABASE_PASSWORD"] %>